### ISSUE TITLE
Cannot import OAuthHandler

### ISSUE THREAD

**Issue by brw31415** [agalea91/twitter_search#1]
hi, i keep getting this error, although  i conformed tweepy is installed:

python3 /home/ubuntu/workspace/scrape-tweet.py
_NamespacePath(['/home/ubuntu/workspace/tweepy'])
Traceback (most recent call last):
  File "/home/ubuntu/workspace/scrape-tweet.py", line 6, in <module>
    from tweepy import OAuthHandler
ImportError: cannot import name 'OAuthHandler'

tweepy is cloned to tweepy dir nder my working dir

**Comment by zazencodes** [comment]
Hi, I'm not sure how much this question has to do with my project as I see you are using a file named scrape-tweet.py (my file is twitter_search.py). Regardless, have you tried importing tweepy on its own? i.e. import tweepy .  If this doesn't work then your problem has more to do with tweepy and you need to make sure it's installed properly. I can let you know that, unlike yourself, I'm using Windows. Also I installed python via the Anaconda distribution.

**Comment by brw31415** [comment]
thanks for your kind reply, and you are right it has nothing to do with
your project i am not too familiar with python, but i fixed it after
realizing that pip3 (not pip) required to install the correct tweepy for
python  3
